package scanner

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/sydlexius/canticle/internal/lyrics"
	"github.com/sydlexius/canticle/internal/queue"
)

// minimalID3v2 is a minimal ID3v2.3 tag with TIT2 ("Test Title") and TPE1
// ("Test Artist") frames. dhowden/tag parses this without error.
// Generated by encoding TIT2 + TPE1 frames into a syncsafe-size ID3v2.3 header.
var minimalID3v2 = []byte{
	0x49, 0x44, 0x33, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x2b, // ID3v2.3 header, syncsafe size=43
	0x54, 0x49, 0x54, 0x32, 0x00, 0x00, 0x00, 0x0b, 0x00, 0x00, // TIT2 frame header (size=11)
	0x00, 0x54, 0x65, 0x73, 0x74, 0x20, 0x54, 0x69, 0x74, 0x6c, 0x65, // encoding + "Test Title"
	0x54, 0x50, 0x45, 0x31, 0x00, 0x00, 0x00, 0x0c, 0x00, 0x00, // TPE1 frame header (size=12)
	0x00, 0x54, 0x65, 0x73, 0x74, 0x20, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, // encoding + "Test Artist"
}

// writeAudioFile creates a minimal .mp3 in dir with a valid ID3v2 header.
func writeAudioFile(t *testing.T, dir, name string) {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, minimalID3v2, 0o644); err != nil {
		t.Fatalf("writeAudioFile %s: %v", path, err)
	}
}

// touchFile creates an empty file in dir.
func touchFile(t *testing.T, dir, name string) {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, nil, 0o644); err != nil {
		t.Fatalf("touchFile %s: %v", path, err)
	}
}

// writeInstrumentalTxt creates a .txt sidecar in dir with the plain instrumental
// marker (matching what lyrics.writeInstrumental emits: marker + newline).
func writeInstrumentalTxt(t *testing.T, dir, name string) {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, []byte(lyrics.InstrumentalMarker+"\n"), 0o644); err != nil {
		t.Fatalf("writeInstrumentalTxt %s: %v", path, err)
	}
}

// writeRenamedLRCInstrumentalTxt creates a .txt sidecar in dir that looks like a
// .lrc file renamed to .txt (LRC tag headers followed by the marker line).
// This is the format produced by the #199 cleanup of the ~2 k incorrectly-written .lrc files.
func writeRenamedLRCInstrumentalTxt(t *testing.T, dir, name string) {
	t.Helper()
	path := filepath.Join(dir, name)
	content := "[by:fashni]\n[ar:X]\n[ti:Y]\n[al:Z]\n[length:00:01]\n[00:00.00]" + lyrics.InstrumentalMarker + "\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("writeRenamedLRCInstrumentalTxt %s: %v", path, err)
	}
}

// TestGetSongDir_SkipLogic covers the 12-case skip-logic matrix:
// flags: (update, upgrade) × file states: (none, lrcOnly, txtOnly, both).
//
// Expected enqueue decisions (true = item added to queue):
//
//	update=false, upgrade=false:
//	  none      → true   (no existing lyrics, fetch fresh)
//	  lrcOnly   → false  (lrc present, not updating)
//	  txtOnly   → false  (txt present, not upgrading)
//	  both      → false  (lrc present, not updating)
//
//	update=false, upgrade=true:
//	  none      → true
//	  lrcOnly   → false  (lrc present, not updating)
//	  txtOnly   → true   (txt present, upgrade requested)
//	  both      → false  (lrc present, not updating)
//
//	update=true, upgrade=false (--update implies --upgrade):
//	  none      → true
//	  lrcOnly   → true   (update requested)
//	  txtOnly   → true   (update implies upgrade)
//	  both      → true
//
//	update=true, upgrade=true:
//	  (same as update=true, upgrade=false — all four cases enqueue)
func TestGetSongDir_SkipLogic(t *testing.T) {
	tests := []struct {
		name              string
		update            bool
		upgrade           bool
		lrcExists         bool
		txtExists         bool
		txtIsInstrumental bool
		txtIsRenamedLRC   bool
		wantQueue         bool
	}{
		// update=false, upgrade=false
		{name: "no_flags_no_files", update: false, upgrade: false, lrcExists: false, txtExists: false, wantQueue: true},
		{name: "no_flags_lrc_only", update: false, upgrade: false, lrcExists: true, txtExists: false, wantQueue: false},
		{name: "no_flags_txt_only", update: false, upgrade: false, lrcExists: false, txtExists: true, wantQueue: false},
		{name: "no_flags_both", update: false, upgrade: false, lrcExists: true, txtExists: true, wantQueue: false},

		// update=false, upgrade=true
		{name: "upgrade_no_files", update: false, upgrade: true, lrcExists: false, txtExists: false, wantQueue: true},
		{name: "upgrade_lrc_only", update: false, upgrade: true, lrcExists: true, txtExists: false, wantQueue: false},
		{name: "upgrade_txt_only", update: false, upgrade: true, lrcExists: false, txtExists: true, wantQueue: true},
		{name: "upgrade_both", update: false, upgrade: true, lrcExists: true, txtExists: true, wantQueue: false},
		// Instrumental .txt markers are terminal -- must not be re-queued even with --upgrade.
		{name: "upgrade_txt_only_instrumental", update: false, upgrade: true, lrcExists: false, txtExists: true, txtIsInstrumental: true, wantQueue: false},
		// Files renamed from .lrc carry LRC tag headers before the marker line --
		// substring match must still detect them as instrumental and skip.
		{name: "upgrade_txt_renamed_lrc_instrumental", update: false, upgrade: true, lrcExists: false, txtExists: true, txtIsRenamedLRC: true, wantQueue: false},

		// update=true, upgrade=false
		{name: "update_no_files", update: true, upgrade: false, lrcExists: false, txtExists: false, wantQueue: true},
		{name: "update_lrc_only", update: true, upgrade: false, lrcExists: true, txtExists: false, wantQueue: true},
		{name: "update_txt_only", update: true, upgrade: false, lrcExists: false, txtExists: true, wantQueue: true},
		{name: "update_both", update: true, upgrade: false, lrcExists: true, txtExists: true, wantQueue: true},
		// --update is an explicit full re-fetch; instrumental markers do not block it.
		{name: "update_txt_only_instrumental", update: true, upgrade: false, lrcExists: false, txtExists: true, txtIsInstrumental: true, wantQueue: true},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			writeAudioFile(t, dir, "track.mp3")
			if tc.lrcExists {
				touchFile(t, dir, "track.lrc")
			}
			if tc.txtExists {
				switch {
				case tc.txtIsRenamedLRC:
					writeRenamedLRCInstrumentalTxt(t, dir, "track.txt")
				case tc.txtIsInstrumental:
					writeInstrumentalTxt(t, dir, "track.txt")
				default:
					touchFile(t, dir, "track.txt")
				}
			}

			q := queue.NewInputsQueue()
			sc := NewScanner()
			// depth=0, limit=100, bfs=false
			if err := sc.GetSongDir(dir, q, tc.update, tc.upgrade, 100, 0, false); err != nil {
				t.Fatalf("GetSongDir returned error: %v", err)
			}

			gotQueue := q.Len() > 0
			if gotQueue != tc.wantQueue {
				t.Errorf("update=%v upgrade=%v lrc=%v txt=%v: got enqueued=%v, want enqueued=%v",
					tc.update, tc.upgrade, tc.lrcExists, tc.txtExists, gotQueue, tc.wantQueue)
			}
		})
	}
}

func TestScanLibrary_ReturnsStructuredResults(t *testing.T) {
	dir := t.TempDir()
	writeAudioFile(t, dir, "track.mp3")

	sc := NewScanner()
	results, err := sc.ScanLibrary(context.Background(), dir, ScanOptions{MaxDepth: 100})
	if err != nil {
		t.Fatalf("ScanLibrary: %v", err)
	}
	if len(results) != 1 {
		t.Fatalf("ScanLibrary returned %d results; want 1", len(results))
	}
	got := results[0]
	if got.FilePath != filepath.Join(dir, "track.mp3") {
		t.Errorf("FilePath = %q; want %q", got.FilePath, filepath.Join(dir, "track.mp3"))
	}
	if got.Outdir != dir {
		t.Errorf("Outdir = %q; want %q", got.Outdir, dir)
	}
	if got.Filename != "track.lrc" {
		t.Errorf("Filename = %q; want %q", got.Filename, "track.lrc")
	}
	if got.Track.ArtistName != "Test Artist" || got.Track.TrackName != "Test Title" {
		t.Errorf("Track = %+v; want Test Artist/Test Title", got.Track)
	}
	if got.Status != "pending" {
		t.Errorf("Status = %q; want pending", got.Status)
	}
}

func TestScanLibrary_RespectsMaxDepth(t *testing.T) {
	root := t.TempDir()
	nested := filepath.Join(root, "nested")
	if err := os.Mkdir(nested, 0o755); err != nil {
		t.Fatalf("mkdir nested: %v", err)
	}
	writeAudioFile(t, nested, "track.mp3")

	sc := NewScanner()
	results, err := sc.ScanLibrary(context.Background(), root, ScanOptions{MaxDepth: 0})
	if err != nil {
		t.Fatalf("ScanLibrary: %v", err)
	}
	if len(results) != 0 {
		t.Fatalf("ScanLibrary returned %d results; want 0", len(results))
	}
}

func TestScanLibrary_RespectsCanceledContext(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	sc := NewScanner()
	_, err := sc.ScanLibrary(ctx, t.TempDir(), ScanOptions{MaxDepth: 100})
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("ScanLibrary error = %v; want context.Canceled", err)
	}
}

// TestAudioFileTypeForExt covers every branch of the audioFileTypeForExt
// switch including the default (unknown extension) path.
func TestAudioFileTypeForExt(t *testing.T) {
	cases := []struct {
		ext    string
		wantOK bool
	}{
		{".flac", true},
		{".mp3", true},
		{".m4a", true},
		{".m4b", true},
		{".m4p", true},
		{".alac", true},
		{".ogg", true},
		{".dsf", true},
		{".wav", false},
		{"", false},
	}
	for _, tc := range cases {
		ft, ok := audioFileTypeForExt(tc.ext)
		if ok != tc.wantOK {
			t.Errorf("audioFileTypeForExt(%q) ok=%v, want %v", tc.ext, ok, tc.wantOK)
		}
		if !ok && ft != 0 {
			t.Errorf("audioFileTypeForExt(%q) returned non-zero type on miss: %d", tc.ext, ft)
		}
	}
}

// writeMarkerWithHeader writes an instrumental .txt with a provenance header,
// mirroring what the Unit A writer emits: [by:canticle], an optional [source:],
// an optional [dv:], then the marker line.
func writeMarkerWithHeader(t *testing.T, dir, name, source, dv string) {
	t.Helper()
	var b strings.Builder
	b.WriteString("[by:canticle]\n")
	if source != "" {
		b.WriteString("[source:" + source + "]\n")
	}
	if dv != "" {
		b.WriteString("[dv:" + dv + "]\n")
	}
	b.WriteString(lyrics.InstrumentalMarker + "\n")
	if err := os.WriteFile(filepath.Join(dir, name), []byte(b.String()), 0o644); err != nil {
		t.Fatalf("writeMarkerWithHeader %s: %v", name, err)
	}
}

// TestScanLibrary_InstrumentalProvenanceReopen verifies provenance-aware
// re-check eligibility (#502): a detector marker is provisional (reopens on
// --upgrade or a detector-version bump), a provider/legacy marker is terminal
// (reopens only on --update).
func TestScanLibrary_InstrumentalProvenanceReopen(t *testing.T) {
	cases := []struct {
		name        string
		source      string
		dv          string
		opts        ScanOptions
		wantEnqueue bool
	}{
		{"detector_upgrade_reopens", lyrics.SourceDetector, "1.0", ScanOptions{Upgrade: true}, true},
		{"detector_no_flags_terminal", lyrics.SourceDetector, "1.0", ScanOptions{}, false},
		{"detector_version_bump_reopens", lyrics.SourceDetector, "1.0", ScanOptions{DetectorVersion: "2.0"}, true},
		{"detector_same_version_terminal", lyrics.SourceDetector, "1.0", ScanOptions{DetectorVersion: "1.0"}, false},
		{"provider_upgrade_terminal", "musixmatch", "", ScanOptions{Upgrade: true}, false},
		{"provider_update_reopens", "musixmatch", "", ScanOptions{Update: true}, true},
		{"legacy_bare_upgrade_terminal", "", "", ScanOptions{Upgrade: true}, false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			writeAudioFile(t, dir, "song.mp3")
			writeMarkerWithHeader(t, dir, "song.txt", tc.source, tc.dv)
			sc := NewScanner()
			results, err := sc.ScanLibrary(context.Background(), dir, tc.opts)
			if err != nil {
				t.Fatalf("ScanLibrary: %v", err)
			}
			gotEnqueue := len(results) > 0
			if gotEnqueue != tc.wantEnqueue {
				t.Errorf("source=%q dv=%q opts=%+v: enqueued=%v, want %v", tc.source, tc.dv, tc.opts, gotEnqueue, tc.wantEnqueue)
			}
		})
	}
}

// TestScanLibrary_UnsyncedBefore covers the dated repair filter (#617): --upgrade
// reopens an unsynced .txt, and UnsyncedBefore narrows a single run to sidecars
// written before a cutoff so a one-time repair of a historical cohort does not
// re-fetch (and rewrite the mtime of) sidecars already known to be correct.
func TestScanLibrary_UnsyncedBefore(t *testing.T) {
	cutoff := time.Date(2026, 4, 1, 0, 0, 0, 0, time.UTC)
	old := time.Date(2026, 3, 15, 0, 0, 0, 0, time.UTC)
	recent := time.Date(2026, 6, 15, 0, 0, 0, 0, time.UTC)

	cases := []struct {
		name        string
		sidecarTime time.Time
		opts        ScanOptions
		wantEnqueue bool
	}{
		// The filter narrows an upgrade run to the pre-cutoff cohort.
		{"old_sidecar_within_window_reopens", old, ScanOptions{Upgrade: true, UnsyncedBefore: cutoff}, true},
		{"recent_sidecar_outside_window_skipped", recent, ScanOptions{Upgrade: true, UnsyncedBefore: cutoff}, false},
		// Zero value must be inert: unfiltered --upgrade keeps reopening everything,
		// so serve mode and a plain CLI upgrade are unaffected.
		{"zero_value_reopens_recent", recent, ScanOptions{Upgrade: true}, true},
		{"zero_value_reopens_old", old, ScanOptions{Upgrade: true}, true},
		// The filter must not resurrect a class the reopen rules exclude.
		{"no_upgrade_flag_stays_terminal", old, ScanOptions{UnsyncedBefore: cutoff}, false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			writeAudioFile(t, dir, "song.mp3")
			txt := filepath.Join(dir, "song.txt")
			if err := os.WriteFile(txt, []byte("an unsynced lyric body\n"), 0o644); err != nil {
				t.Fatalf("write sidecar: %v", err)
			}
			if err := os.Chtimes(txt, tc.sidecarTime, tc.sidecarTime); err != nil {
				t.Fatalf("chtimes: %v", err)
			}
			sc := NewScanner()
			results, err := sc.ScanLibrary(context.Background(), dir, tc.opts)
			if err != nil {
				t.Fatalf("ScanLibrary: %v", err)
			}
			if got := len(results) > 0; got != tc.wantEnqueue {
				t.Errorf("sidecar mtime=%s opts=%+v: enqueued=%v, want %v",
					tc.sidecarTime.Format("2006-01"), tc.opts, got, tc.wantEnqueue)
			}
		})
	}
}

// TestSidecarWithinWindow covers the repair-window predicate directly, including
// the fail-closed stat-error branch that ScanLibrary cannot reach (it only calls
// this after its own os.Stat already succeeded).
func TestSidecarWithinWindow(t *testing.T) {
	cutoff := time.Date(2026, 4, 1, 0, 0, 0, 0, time.UTC)
	dir := t.TempDir()

	before := filepath.Join(dir, "before.txt")
	if err := os.WriteFile(before, []byte("x"), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	old := time.Date(2026, 3, 15, 0, 0, 0, 0, time.UTC)
	if err := os.Chtimes(before, old, old); err != nil {
		t.Fatalf("chtimes: %v", err)
	}

	after := filepath.Join(dir, "after.txt")
	if err := os.WriteFile(after, []byte("x"), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	recent := time.Date(2026, 6, 15, 0, 0, 0, 0, time.UTC)
	if err := os.Chtimes(after, recent, recent); err != nil {
		t.Fatalf("chtimes: %v", err)
	}

	exact := filepath.Join(dir, "exact.txt")
	if err := os.WriteFile(exact, []byte("x"), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	if err := os.Chtimes(exact, cutoff, cutoff); err != nil {
		t.Fatalf("chtimes: %v", err)
	}

	missing := filepath.Join(dir, "does-not-exist.txt")

	cases := []struct {
		name   string
		path   string
		cutoff time.Time
		want   bool
	}{
		{"zero cutoff disables the filter", after, time.Time{}, true},
		{"zero cutoff ignores a missing file", missing, time.Time{}, true},
		{"mtime before cutoff is in window", before, cutoff, true},
		{"mtime after cutoff is out of window", after, cutoff, false},
		// The comparison is strict (time.Before), matching the flag's "before"
		// wording: a sidecar stamped exactly at the cutoff is excluded. This is the
		// boundary most likely to regress silently, since flipping Before to
		// !After would keep every other case in this table passing.
		{"mtime equal to cutoff is out of window (strict)", exact, cutoff, false},
		// Fail closed: a bulk repair must only touch files positively identified
		// as belonging to the cohort, so an unstattable sidecar is left alone.
		{"unreadable sidecar fails closed", missing, cutoff, false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := sidecarWithinWindow(tc.path, tc.cutoff); got != tc.want {
				t.Errorf("sidecarWithinWindow = %v, want %v", got, tc.want)
			}
		})
	}
}

// TestScanLibrary_UnsyncedBefore_InstrumentalMarkers covers the repair window's
// effect on provisional (detector-written) instrumental markers. A dated run must
// narrow these too: rewriting a recent marker bumps its mtime and destroys the
// same evidence the cutoff depends on.
//
// An authoritative (provider or legacy bare) marker stays terminal under --upgrade
// regardless of the window, so the cutoff must not resurrect one.
func TestScanLibrary_UnsyncedBefore_InstrumentalMarkers(t *testing.T) {
	cutoff := time.Date(2026, 4, 1, 0, 0, 0, 0, time.UTC)
	old := time.Date(2026, 3, 15, 0, 0, 0, 0, time.UTC)
	recent := time.Date(2026, 6, 15, 0, 0, 0, 0, time.UTC)

	cases := []struct {
		name        string
		source      string
		markerTime  time.Time
		opts        ScanOptions
		wantEnqueue bool
	}{
		// The gap this test was written for: without the window check inside the
		// instrumental branch, a recent provisional marker is reopened by a dated
		// run and rewritten, destroying its mtime.
		{"provisional_recent_outside_window_skipped", lyrics.SourceDetector, recent,
			ScanOptions{Upgrade: true, UnsyncedBefore: cutoff}, false},
		{"provisional_old_within_window_reopens", lyrics.SourceDetector, old,
			ScanOptions{Upgrade: true, UnsyncedBefore: cutoff}, true},
		// Zero value stays inert for markers too.
		{"provisional_recent_no_cutoff_reopens", lyrics.SourceDetector, recent,
			ScanOptions{Upgrade: true}, true},
		// The window must never resurrect a terminal class.
		{"authoritative_old_within_window_stays_terminal", "musixmatch", old,
			ScanOptions{Upgrade: true, UnsyncedBefore: cutoff}, false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			writeAudioFile(t, dir, "song.mp3")
			writeMarkerWithHeader(t, dir, "song.txt", tc.source, "1.0")
			marker := filepath.Join(dir, "song.txt")
			if err := os.Chtimes(marker, tc.markerTime, tc.markerTime); err != nil {
				t.Fatalf("chtimes: %v", err)
			}
			sc := NewScanner()
			results, err := sc.ScanLibrary(context.Background(), dir, tc.opts)
			if err != nil {
				t.Fatalf("ScanLibrary: %v", err)
			}
			if got := len(results) > 0; got != tc.wantEnqueue {
				t.Errorf("source=%q mtime=%s opts=%+v: enqueued=%v, want %v",
					tc.source, tc.markerTime.Format("2006-01"), tc.opts, got, tc.wantEnqueue)
			}
		})
	}
}

// TestScanLibrary_WindowNeverResurrectsATerminalClass guards the ordering
// invariant directly. The window check must run only INSIDE a branch that already
// granted a reopen, so a sidecar the reopen rules exclude stays excluded no matter
// what the cutoff says.
//
// The load-bearing case is the recent sidecar with NO reopen flag: an earlier
// revision expressed the window as a sibling switch case, and hoisting that case
// above the reopen check let an out-of-window file reach enqueue for the wrong
// reason. Every case here must stay non-enqueued because the class was never
// reopened -- never because the mtime happened to agree.
func TestScanLibrary_WindowNeverResurrectsATerminalClass(t *testing.T) {
	cutoff := time.Date(2026, 4, 1, 0, 0, 0, 0, time.UTC)
	old := time.Date(2026, 3, 15, 0, 0, 0, 0, time.UTC)
	recent := time.Date(2026, 6, 15, 0, 0, 0, 0, time.UTC)

	cases := []struct {
		name        string
		sidecarTime time.Time
	}{
		{"in_window_sidecar_without_reopen_stays_terminal", old},
		{"out_of_window_sidecar_without_reopen_stays_terminal", recent},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			writeAudioFile(t, dir, "song.mp3")
			txt := filepath.Join(dir, "song.txt")
			if err := os.WriteFile(txt, []byte("an unsynced lyric body\n"), 0o644); err != nil {
				t.Fatalf("write sidecar: %v", err)
			}
			if err := os.Chtimes(txt, tc.sidecarTime, tc.sidecarTime); err != nil {
				t.Fatalf("chtimes: %v", err)
			}
			sc := NewScanner()
			// No Upgrade, no Update: the Unsynced class is never reopened, so the
			// cutoff must not matter in either direction.
			results, err := sc.ScanLibrary(context.Background(), dir, ScanOptions{UnsyncedBefore: cutoff})
			if err != nil {
				t.Fatalf("ScanLibrary: %v", err)
			}
			if len(results) > 0 {
				t.Errorf("mtime=%s: enqueued without a reopen flag; the window must never resurrect a terminal class",
					tc.sidecarTime.Format("2006-01"))
			}
		})
	}
}
