package scanner

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"

	"github.com/sydlexius/canticle/internal/lyrics"
	"github.com/sydlexius/canticle/internal/pathutil"
	"github.com/sydlexius/canticle/internal/queue"
	"github.com/sydlexius/canticle/internal/testutil"
)

// minimalID3v2 is a minimal ID3v2.3 tag with TIT2 ("Test Title") and TPE1
// ("Test Artist") frames. dhowden/tag parses this without error.
// Generated by encoding TIT2 + TPE1 frames into a syncsafe-size ID3v2.3 header.
var minimalID3v2 = []byte{
	0x49, 0x44, 0x33, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x2b, // ID3v2.3 header, syncsafe size=43
	0x54, 0x49, 0x54, 0x32, 0x00, 0x00, 0x00, 0x0b, 0x00, 0x00, // TIT2 frame header (size=11)
	0x00, 0x54, 0x65, 0x73, 0x74, 0x20, 0x54, 0x69, 0x74, 0x6c, 0x65, // encoding + "Test Title"
	0x54, 0x50, 0x45, 0x31, 0x00, 0x00, 0x00, 0x0c, 0x00, 0x00, // TPE1 frame header (size=12)
	0x00, 0x54, 0x65, 0x73, 0x74, 0x20, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, // encoding + "Test Artist"
}

// writeAudioFile creates a minimal .mp3 in dir with a valid ID3v2 header.
func writeAudioFile(t *testing.T, dir, name string) {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, minimalID3v2, 0o644); err != nil {
		t.Fatalf("writeAudioFile %s: %v", path, err)
	}
}

// touchFile creates an empty file in dir.
func touchFile(t *testing.T, dir, name string) {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, nil, 0o644); err != nil {
		t.Fatalf("touchFile %s: %v", path, err)
	}
}

// writeInstrumentalTxt creates a .txt sidecar in dir with the plain instrumental
// marker (matching what lyrics.writeInstrumental emits: marker + newline).
func writeInstrumentalTxt(t *testing.T, dir, name string) {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, []byte(lyrics.InstrumentalMarker+"\n"), 0o644); err != nil {
		t.Fatalf("writeInstrumentalTxt %s: %v", path, err)
	}
}

// writeRenamedLRCInstrumentalTxt creates a .txt sidecar in dir that looks like a
// .lrc file renamed to .txt (LRC tag headers followed by the marker line).
// This is the format produced by the #199 cleanup of the ~2 k incorrectly-written .lrc files.
func writeRenamedLRCInstrumentalTxt(t *testing.T, dir, name string) {
	t.Helper()
	path := filepath.Join(dir, name)
	content := "[by:fashni]\n[ar:X]\n[ti:Y]\n[al:Z]\n[length:00:01]\n[00:00.00]" + lyrics.InstrumentalMarker + "\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("writeRenamedLRCInstrumentalTxt %s: %v", path, err)
	}
}

// TestGetSongDir_SkipLogic covers the 12-case skip-logic matrix:
// flags: (update, upgrade) × file states: (none, lrcOnly, txtOnly, both).
//
// Expected enqueue decisions (true = item added to queue):
//
//	update=false, upgrade=false:
//	  none      → true   (no existing lyrics, fetch fresh)
//	  lrcOnly   → false  (lrc present, not updating)
//	  txtOnly   → false  (txt present, not upgrading)
//	  both      → false  (lrc present, not updating)
//
//	update=false, upgrade=true:
//	  none      → true
//	  lrcOnly   → false  (lrc present, not updating)
//	  txtOnly   → true   (txt present, upgrade requested)
//	  both      → false  (lrc present, not updating)
//
//	update=true, upgrade=false (--update implies --upgrade):
//	  none      → true
//	  lrcOnly   → true   (update requested)
//	  txtOnly   → true   (update implies upgrade)
//	  both      → true
//
//	update=true, upgrade=true:
//	  (same as update=true, upgrade=false — all four cases enqueue)
func TestGetSongDir_SkipLogic(t *testing.T) {
	tests := []struct {
		name              string
		update            bool
		upgrade           bool
		lrcExists         bool
		txtExists         bool
		txtIsInstrumental bool
		txtIsRenamedLRC   bool
		wantQueue         bool
	}{
		// update=false, upgrade=false
		{name: "no_flags_no_files", update: false, upgrade: false, lrcExists: false, txtExists: false, wantQueue: true},
		{name: "no_flags_lrc_only", update: false, upgrade: false, lrcExists: true, txtExists: false, wantQueue: false},
		{name: "no_flags_txt_only", update: false, upgrade: false, lrcExists: false, txtExists: true, wantQueue: false},
		{name: "no_flags_both", update: false, upgrade: false, lrcExists: true, txtExists: true, wantQueue: false},

		// update=false, upgrade=true
		{name: "upgrade_no_files", update: false, upgrade: true, lrcExists: false, txtExists: false, wantQueue: true},
		{name: "upgrade_lrc_only", update: false, upgrade: true, lrcExists: true, txtExists: false, wantQueue: false},
		{name: "upgrade_txt_only", update: false, upgrade: true, lrcExists: false, txtExists: true, wantQueue: true},
		{name: "upgrade_both", update: false, upgrade: true, lrcExists: true, txtExists: true, wantQueue: false},
		// Instrumental .txt markers are terminal -- must not be re-queued even with --upgrade.
		{name: "upgrade_txt_only_instrumental", update: false, upgrade: true, lrcExists: false, txtExists: true, txtIsInstrumental: true, wantQueue: false},
		// Files renamed from .lrc carry LRC tag headers before the marker line --
		// substring match must still detect them as instrumental and skip.
		{name: "upgrade_txt_renamed_lrc_instrumental", update: false, upgrade: true, lrcExists: false, txtExists: true, txtIsRenamedLRC: true, wantQueue: false},

		// update=true, upgrade=false
		{name: "update_no_files", update: true, upgrade: false, lrcExists: false, txtExists: false, wantQueue: true},
		{name: "update_lrc_only", update: true, upgrade: false, lrcExists: true, txtExists: false, wantQueue: true},
		{name: "update_txt_only", update: true, upgrade: false, lrcExists: false, txtExists: true, wantQueue: true},
		{name: "update_both", update: true, upgrade: false, lrcExists: true, txtExists: true, wantQueue: true},
		// --update is an explicit full re-fetch; instrumental markers do not block it.
		{name: "update_txt_only_instrumental", update: true, upgrade: false, lrcExists: false, txtExists: true, txtIsInstrumental: true, wantQueue: true},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			writeAudioFile(t, dir, "track.mp3")
			if tc.lrcExists {
				touchFile(t, dir, "track.lrc")
			}
			if tc.txtExists {
				switch {
				case tc.txtIsRenamedLRC:
					writeRenamedLRCInstrumentalTxt(t, dir, "track.txt")
				case tc.txtIsInstrumental:
					writeInstrumentalTxt(t, dir, "track.txt")
				default:
					touchFile(t, dir, "track.txt")
				}
			}

			q := queue.NewInputsQueue()
			sc := NewScanner()
			// depth=0, limit=100, bfs=false
			if err := sc.GetSongDir(dir, q, tc.update, tc.upgrade, 100, 0, false); err != nil {
				t.Fatalf("GetSongDir returned error: %v", err)
			}

			gotQueue := q.Len() > 0
			if gotQueue != tc.wantQueue {
				t.Errorf("update=%v upgrade=%v lrc=%v txt=%v: got enqueued=%v, want enqueued=%v",
					tc.update, tc.upgrade, tc.lrcExists, tc.txtExists, gotQueue, tc.wantQueue)
			}
		})
	}
}

func TestScanLibrary_ReturnsStructuredResults(t *testing.T) {
	dir := t.TempDir()
	writeAudioFile(t, dir, "track.mp3")

	sc := NewScanner()
	results, err := sc.ScanLibrary(context.Background(), dir, ScanOptions{MaxDepth: 100})
	if err != nil {
		t.Fatalf("ScanLibrary: %v", err)
	}
	if len(results) != 1 {
		t.Fatalf("ScanLibrary returned %d results; want 1", len(results))
	}
	got := results[0]
	if got.FilePath != filepath.Join(dir, "track.mp3") {
		t.Errorf("FilePath = %q; want %q", got.FilePath, filepath.Join(dir, "track.mp3"))
	}
	if got.Outdir != dir {
		t.Errorf("Outdir = %q; want %q", got.Outdir, dir)
	}
	if got.Filename != "track.lrc" {
		t.Errorf("Filename = %q; want %q", got.Filename, "track.lrc")
	}
	if got.Track.ArtistName != "Test Artist" || got.Track.TrackName != "Test Title" {
		t.Errorf("Track = %+v; want Test Artist/Test Title", got.Track)
	}
	if got.Status != "pending" {
		t.Errorf("Status = %q; want pending", got.Status)
	}
}

func TestScanLibrary_RespectsMaxDepth(t *testing.T) {
	root := t.TempDir()
	nested := filepath.Join(root, "nested")
	if err := os.Mkdir(nested, 0o755); err != nil {
		t.Fatalf("mkdir nested: %v", err)
	}
	writeAudioFile(t, nested, "track.mp3")

	sc := NewScanner()
	results, err := sc.ScanLibrary(context.Background(), root, ScanOptions{MaxDepth: 0})
	if err != nil {
		t.Fatalf("ScanLibrary: %v", err)
	}
	if len(results) != 0 {
		t.Fatalf("ScanLibrary returned %d results; want 0", len(results))
	}
}

func TestScanLibrary_RespectsCanceledContext(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	sc := NewScanner()
	_, err := sc.ScanLibrary(ctx, t.TempDir(), ScanOptions{MaxDepth: 100})
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("ScanLibrary error = %v; want context.Canceled", err)
	}
}

// TestAudioFileTypeForExt covers every branch of the audioFileTypeForExt
// switch including the default (unknown extension) path.
func TestAudioFileTypeForExt(t *testing.T) {
	cases := []struct {
		ext    string
		wantOK bool
	}{
		{".flac", true},
		{".mp3", true},
		{".m4a", true},
		{".m4b", true},
		{".m4p", true},
		{".alac", true},
		{".ogg", true},
		{".dsf", true},
		{".wav", false},
		{"", false},
	}
	for _, tc := range cases {
		ft, ok := audioFileTypeForExt(tc.ext)
		if ok != tc.wantOK {
			t.Errorf("audioFileTypeForExt(%q) ok=%v, want %v", tc.ext, ok, tc.wantOK)
		}
		if !ok && ft != 0 {
			t.Errorf("audioFileTypeForExt(%q) returned non-zero type on miss: %d", tc.ext, ft)
		}
	}
}

// writeMarkerWithHeader writes an instrumental .txt with a provenance header,
// mirroring what the Unit A writer emits: [by:canticle], an optional [source:],
// an optional [dv:], then the marker line.
func writeMarkerWithHeader(t *testing.T, dir, name, source, dv string) {
	t.Helper()
	var b strings.Builder
	b.WriteString("[by:canticle]\n")
	if source != "" {
		b.WriteString("[source:" + source + "]\n")
	}
	if dv != "" {
		b.WriteString("[dv:" + dv + "]\n")
	}
	b.WriteString(lyrics.InstrumentalMarker + "\n")
	if err := os.WriteFile(filepath.Join(dir, name), []byte(b.String()), 0o644); err != nil {
		t.Fatalf("writeMarkerWithHeader %s: %v", name, err)
	}
}

// TestScanLibrary_InstrumentalProvenanceReopen verifies provenance-aware
// re-check eligibility (#502): a detector marker is provisional (reopens on
// --upgrade or a detector-version bump), a provider/legacy marker is terminal
// (reopens only on --update).
func TestScanLibrary_InstrumentalProvenanceReopen(t *testing.T) {
	cases := []struct {
		name        string
		source      string
		dv          string
		opts        ScanOptions
		wantEnqueue bool
	}{
		{"detector_upgrade_reopens", lyrics.SourceDetector, "1.0", ScanOptions{Upgrade: true}, true},
		{"detector_no_flags_terminal", lyrics.SourceDetector, "1.0", ScanOptions{}, false},
		{"detector_version_bump_reopens", lyrics.SourceDetector, "1.0", ScanOptions{DetectorVersion: "2.0"}, true},
		{"detector_same_version_terminal", lyrics.SourceDetector, "1.0", ScanOptions{DetectorVersion: "1.0"}, false},
		{"provider_upgrade_terminal", "musixmatch", "", ScanOptions{Upgrade: true}, false},
		{"provider_update_reopens", "musixmatch", "", ScanOptions{Update: true}, true},
		{"legacy_bare_upgrade_terminal", "", "", ScanOptions{Upgrade: true}, false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			writeAudioFile(t, dir, "song.mp3")
			writeMarkerWithHeader(t, dir, "song.txt", tc.source, tc.dv)
			sc := NewScanner()
			results, err := sc.ScanLibrary(context.Background(), dir, tc.opts)
			if err != nil {
				t.Fatalf("ScanLibrary: %v", err)
			}
			gotEnqueue := len(results) > 0
			if gotEnqueue != tc.wantEnqueue {
				t.Errorf("source=%q dv=%q opts=%+v: enqueued=%v, want %v", tc.source, tc.dv, tc.opts, gotEnqueue, tc.wantEnqueue)
			}
		})
	}
}

// TestScanLibrary_UnsyncedBefore covers the dated repair filter (#617): --upgrade
// reopens an unsynced .txt, and UnsyncedBefore narrows a single run to sidecars
// written before a cutoff so a one-time repair of a historical cohort does not
// re-fetch (and rewrite the mtime of) sidecars already known to be correct.
func TestScanLibrary_UnsyncedBefore(t *testing.T) {
	cutoff := time.Date(2026, 4, 1, 0, 0, 0, 0, time.UTC)
	old := time.Date(2026, 3, 15, 0, 0, 0, 0, time.UTC)
	recent := time.Date(2026, 6, 15, 0, 0, 0, 0, time.UTC)

	cases := []struct {
		name        string
		sidecarTime time.Time
		opts        ScanOptions
		wantEnqueue bool
	}{
		// The filter narrows an upgrade run to the pre-cutoff cohort.
		{"old_sidecar_within_window_reopens", old, ScanOptions{Upgrade: true, UnsyncedBefore: cutoff}, true},
		{"recent_sidecar_outside_window_skipped", recent, ScanOptions{Upgrade: true, UnsyncedBefore: cutoff}, false},
		// Zero value must be inert: unfiltered --upgrade keeps reopening everything,
		// so serve mode and a plain CLI upgrade are unaffected.
		{"zero_value_reopens_recent", recent, ScanOptions{Upgrade: true}, true},
		{"zero_value_reopens_old", old, ScanOptions{Upgrade: true}, true},
		// The filter must not resurrect a class the reopen rules exclude.
		{"no_upgrade_flag_stays_terminal", old, ScanOptions{UnsyncedBefore: cutoff}, false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			writeAudioFile(t, dir, "song.mp3")
			txt := filepath.Join(dir, "song.txt")
			if err := os.WriteFile(txt, []byte("an unsynced lyric body\n"), 0o644); err != nil {
				t.Fatalf("write sidecar: %v", err)
			}
			if err := os.Chtimes(txt, tc.sidecarTime, tc.sidecarTime); err != nil {
				t.Fatalf("chtimes: %v", err)
			}
			sc := NewScanner()
			results, err := sc.ScanLibrary(context.Background(), dir, tc.opts)
			if err != nil {
				t.Fatalf("ScanLibrary: %v", err)
			}
			if got := len(results) > 0; got != tc.wantEnqueue {
				t.Errorf("sidecar mtime=%s opts=%+v: enqueued=%v, want %v",
					tc.sidecarTime.Format("2006-01"), tc.opts, got, tc.wantEnqueue)
			}
		})
	}
}

// TestSidecarWithinWindow covers the repair-window predicate directly, including
// the fail-closed stat-error branch that ScanLibrary cannot reach (it only calls
// this after its own os.Stat already succeeded).
func TestSidecarWithinWindow(t *testing.T) {
	cutoff := time.Date(2026, 4, 1, 0, 0, 0, 0, time.UTC)
	dir := t.TempDir()

	before := filepath.Join(dir, "before.txt")
	if err := os.WriteFile(before, []byte("x"), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	old := time.Date(2026, 3, 15, 0, 0, 0, 0, time.UTC)
	if err := os.Chtimes(before, old, old); err != nil {
		t.Fatalf("chtimes: %v", err)
	}

	after := filepath.Join(dir, "after.txt")
	if err := os.WriteFile(after, []byte("x"), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	recent := time.Date(2026, 6, 15, 0, 0, 0, 0, time.UTC)
	if err := os.Chtimes(after, recent, recent); err != nil {
		t.Fatalf("chtimes: %v", err)
	}

	exact := filepath.Join(dir, "exact.txt")
	if err := os.WriteFile(exact, []byte("x"), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	if err := os.Chtimes(exact, cutoff, cutoff); err != nil {
		t.Fatalf("chtimes: %v", err)
	}

	missing := filepath.Join(dir, "does-not-exist.txt")

	cases := []struct {
		name   string
		path   string
		cutoff time.Time
		want   bool
	}{
		{"zero cutoff disables the filter", after, time.Time{}, true},
		{"zero cutoff ignores a missing file", missing, time.Time{}, true},
		{"mtime before cutoff is in window", before, cutoff, true},
		{"mtime after cutoff is out of window", after, cutoff, false},
		// The comparison is strict (time.Before), matching the flag's "before"
		// wording: a sidecar stamped exactly at the cutoff is excluded. This is the
		// boundary most likely to regress silently, since flipping Before to
		// !After would keep every other case in this table passing.
		{"mtime equal to cutoff is out of window (strict)", exact, cutoff, false},
		// Fail closed: a bulk repair must only touch files positively identified
		// as belonging to the cohort, so an unstattable sidecar is left alone.
		{"unreadable sidecar fails closed", missing, cutoff, false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := sidecarWithinWindow(tc.path, tc.cutoff); got != tc.want {
				t.Errorf("sidecarWithinWindow = %v, want %v", got, tc.want)
			}
		})
	}
}

// TestScanLibrary_UnsyncedBefore_InstrumentalMarkers covers the repair window's
// effect on provisional (detector-written) instrumental markers. A dated run must
// narrow these too: rewriting a recent marker bumps its mtime and destroys the
// same evidence the cutoff depends on.
//
// An authoritative (provider or legacy bare) marker stays terminal under --upgrade
// regardless of the window, so the cutoff must not resurrect one.
func TestScanLibrary_UnsyncedBefore_InstrumentalMarkers(t *testing.T) {
	cutoff := time.Date(2026, 4, 1, 0, 0, 0, 0, time.UTC)
	old := time.Date(2026, 3, 15, 0, 0, 0, 0, time.UTC)
	recent := time.Date(2026, 6, 15, 0, 0, 0, 0, time.UTC)

	cases := []struct {
		name        string
		source      string
		markerTime  time.Time
		opts        ScanOptions
		wantEnqueue bool
	}{
		// The gap this test was written for: without the window check inside the
		// instrumental branch, a recent provisional marker is reopened by a dated
		// run and rewritten, destroying its mtime.
		{"provisional_recent_outside_window_skipped", lyrics.SourceDetector, recent,
			ScanOptions{Upgrade: true, UnsyncedBefore: cutoff}, false},
		{"provisional_old_within_window_reopens", lyrics.SourceDetector, old,
			ScanOptions{Upgrade: true, UnsyncedBefore: cutoff}, true},
		// Zero value stays inert for markers too.
		{"provisional_recent_no_cutoff_reopens", lyrics.SourceDetector, recent,
			ScanOptions{Upgrade: true}, true},
		// The window must never resurrect a terminal class.
		{"authoritative_old_within_window_stays_terminal", "musixmatch", old,
			ScanOptions{Upgrade: true, UnsyncedBefore: cutoff}, false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			writeAudioFile(t, dir, "song.mp3")
			writeMarkerWithHeader(t, dir, "song.txt", tc.source, "1.0")
			marker := filepath.Join(dir, "song.txt")
			if err := os.Chtimes(marker, tc.markerTime, tc.markerTime); err != nil {
				t.Fatalf("chtimes: %v", err)
			}
			sc := NewScanner()
			results, err := sc.ScanLibrary(context.Background(), dir, tc.opts)
			if err != nil {
				t.Fatalf("ScanLibrary: %v", err)
			}
			if got := len(results) > 0; got != tc.wantEnqueue {
				t.Errorf("source=%q mtime=%s opts=%+v: enqueued=%v, want %v",
					tc.source, tc.markerTime.Format("2006-01"), tc.opts, got, tc.wantEnqueue)
			}
		})
	}
}

// TestScanLibrary_WindowNeverResurrectsATerminalClass guards the ordering
// invariant directly. The window check must run only INSIDE a branch that already
// granted a reopen, so a sidecar the reopen rules exclude stays excluded no matter
// what the cutoff says.
//
// The load-bearing case is the recent sidecar with NO reopen flag: an earlier
// revision expressed the window as a sibling switch case, and hoisting that case
// above the reopen check let an out-of-window file reach enqueue for the wrong
// reason. Every case here must stay non-enqueued because the class was never
// reopened -- never because the mtime happened to agree.
func TestScanLibrary_WindowNeverResurrectsATerminalClass(t *testing.T) {
	cutoff := time.Date(2026, 4, 1, 0, 0, 0, 0, time.UTC)
	old := time.Date(2026, 3, 15, 0, 0, 0, 0, time.UTC)
	recent := time.Date(2026, 6, 15, 0, 0, 0, 0, time.UTC)

	cases := []struct {
		name        string
		sidecarTime time.Time
	}{
		{"in_window_sidecar_without_reopen_stays_terminal", old},
		{"out_of_window_sidecar_without_reopen_stays_terminal", recent},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			writeAudioFile(t, dir, "song.mp3")
			txt := filepath.Join(dir, "song.txt")
			if err := os.WriteFile(txt, []byte("an unsynced lyric body\n"), 0o644); err != nil {
				t.Fatalf("write sidecar: %v", err)
			}
			if err := os.Chtimes(txt, tc.sidecarTime, tc.sidecarTime); err != nil {
				t.Fatalf("chtimes: %v", err)
			}
			sc := NewScanner()
			// No Upgrade, no Update: the Unsynced class is never reopened, so the
			// cutoff must not matter in either direction.
			results, err := sc.ScanLibrary(context.Background(), dir, ScanOptions{UnsyncedBefore: cutoff})
			if err != nil {
				t.Fatalf("ScanLibrary: %v", err)
			}
			if len(results) > 0 {
				t.Errorf("mtime=%s: enqueued without a reopen flag; the window must never resurrect a terminal class",
					tc.sidecarTime.Format("2006-01"))
			}
		})
	}
}

// recordingDurationStore captures what the scanner banks, so the test asserts on
// the recorded tuple rather than on a DB round-trip.
//
// Lookup is backed by what Record actually stored, and keyed on the full
// (path, mtime, size) tuple exactly like the real table. A stub returning a
// constant would make the skipped-file probe gate (#684) untestable: the whole
// property worth asserting is that a SECOND scan finds the row the first one
// wrote and does not re-probe.
type recordingDurationStore struct {
	paths   []string
	mtimes  []int64
	sizes   []int64
	seconds []int
	// lookupErr, when set, is returned by every Lookup to exercise the
	// fail-closed branch.
	lookupErr error
}

func (r *recordingDurationStore) Record(_ context.Context, path string, mtimeUnixNano, size int64, seconds int) error {
	r.paths = append(r.paths, path)
	r.mtimes = append(r.mtimes, mtimeUnixNano)
	r.sizes = append(r.sizes, size)
	r.seconds = append(r.seconds, seconds)
	return nil
}

func (r *recordingDurationStore) Lookup(_ context.Context, path string, mtimeUnixNano, size int64) (int, bool, error) {
	if r.lookupErr != nil {
		return 0, false, r.lookupErr
	}
	for i, p := range r.paths {
		if p == path && r.mtimes[i] == mtimeUnixNano && r.sizes[i] == size {
			return r.seconds[i], true, nil
		}
	}
	return 0, false, nil
}

// The scanner already computes a duration during enrichment and discards it.
// Banking it costs no extra disk I/O, and is the primary fill path for the
// revalidation cache (#441).
func TestScanRecordsDurationWhenEnriching(t *testing.T) {
	dir := t.TempDir()
	// 44100 Hz * 210s = 9,261,000 samples, so the FLAC header yields an exact
	// 210s duration for audioduration to parse -- no probeFunc override needed.
	const sampleRate, totalSamples uint32 = 44100, 44100 * 210
	if err := testutil.WriteFLACFile(dir, "song.flac", sampleRate, totalSamples); err != nil {
		t.Fatalf("write fixture: %v", err)
	}
	// The cache key is canonicalized (#643: absolute, symlink-resolved root),
	// so it may differ from the literal t.TempDir() spelling -- e.g. on macOS
	// /var is itself a symlink to /private/var. Compare against
	// filepath.EvalSymlinks of the real path rather than the raw join.
	wantPath, err := filepath.EvalSymlinks(filepath.Join(dir, "song.flac"))
	if err != nil {
		t.Fatalf("EvalSymlinks fixture path: %v", err)
	}

	store := &recordingDurationStore{}
	sc := NewScanner(WithDurationStore(store))

	results, err := sc.ScanLibrary(context.Background(), dir, ScanOptions{MaxDepth: 1, EnrichRecording: true})
	if err != nil {
		t.Fatalf("ScanLibrary: %v", err)
	}
	if len(results) != 1 {
		t.Fatalf("got %d results; want 1", len(results))
	}

	if len(store.paths) != 1 {
		t.Fatalf("recorded %d durations, want 1", len(store.paths))
	}
	if store.paths[0] != wantPath {
		t.Fatalf("recorded path %q, want canonical %q", store.paths[0], wantPath)
	}
	if store.seconds[0] != 210 {
		t.Fatalf("recorded %ds, want 210s", store.seconds[0])
	}
}

// A file that already has a .lrc is skipped for FETCHING, but its duration must
// still be banked (#684). This is the coverage gap that starved revalidate: it
// walks SIDECARS and needs each one's companion audio duration, yet the files it
// cares about are exactly the ones the fetch path short-circuits before the
// probe. Measured in prod, a full scan banked 690 new durations and moved
// revalidate's unknown-duration count by ZERO, because the two populations are
// near-disjoint by construction.
func TestScanRecordsDurationForFileWithExistingLRC(t *testing.T) {
	dir := t.TempDir()
	const sampleRate, totalSamples uint32 = 44100, 44100 * 210
	if err := testutil.WriteFLACFile(dir, "song.flac", sampleRate, totalSamples); err != nil {
		t.Fatalf("write fixture: %v", err)
	}
	// The settled sidecar that makes the scanner skip this file for fetching.
	if err := os.WriteFile(filepath.Join(dir, "song.lrc"), []byte("[00:01.00]words\n"), 0o600); err != nil {
		t.Fatalf("write .lrc: %v", err)
	}
	wantPath, err := filepath.EvalSymlinks(filepath.Join(dir, "song.flac"))
	if err != nil {
		t.Fatalf("EvalSymlinks fixture path: %v", err)
	}

	store := &recordingDurationStore{}
	sc := NewScanner(WithDurationStore(store))

	results, err := sc.ScanLibrary(context.Background(), dir, ScanOptions{MaxDepth: 1, EnrichRecording: true})
	if err != nil {
		t.Fatalf("ScanLibrary: %v", err)
	}
	// The track is still correctly SKIPPED for fetching -- this fix must not
	// re-enqueue settled work, only bank the duration.
	if len(results) != 0 {
		t.Fatalf("got %d results; want 0 (a settled .lrc must not be enqueued)", len(results))
	}

	if len(store.paths) != 1 {
		t.Fatalf("recorded %d durations, want 1 (a skipped file still needs its duration banked)", len(store.paths))
	}
	if store.paths[0] != wantPath {
		t.Fatalf("recorded path %q, want canonical %q", store.paths[0], wantPath)
	}
	if store.seconds[0] != 210 {
		t.Fatalf("recorded %ds, want 210s", store.seconds[0])
	}
}

// The Lookup gate is what keeps the #684 fix from causing the symptom #684
// exists to remove. bankDurationForSkippedFile runs for EVERY settled file on
// EVERY scan, so an ungated probe would re-read tens of thousands of headers per
// pass and keep the library disks permanently awake. A second scan over
// unchanged files must therefore probe NOTHING.
func TestScanDoesNotReprobeSkippedFileWithCachedDuration(t *testing.T) {
	dir := t.TempDir()
	const sampleRate, totalSamples uint32 = 44100, 44100 * 210
	if err := testutil.WriteFLACFile(dir, "song.flac", sampleRate, totalSamples); err != nil {
		t.Fatalf("write fixture: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "song.lrc"), []byte("[00:01.00]words\n"), 0o600); err != nil {
		t.Fatalf("write .lrc: %v", err)
	}

	store := &recordingDurationStore{}
	sc := NewScanner(WithDurationStore(store))

	// Count probes directly: the gate's whole purpose is preventing the header
	// READ, so asserting on row count alone would pass even if every scan
	// re-read the file and rewrote an identical row.
	probes := 0
	sc.probeFunc = func(string) (int, error) {
		probes++
		return 210, nil
	}

	opts := ScanOptions{MaxDepth: 1, EnrichRecording: true}
	if _, err := sc.ScanLibrary(context.Background(), dir, opts); err != nil {
		t.Fatalf("first ScanLibrary: %v", err)
	}
	if probes != 1 {
		t.Fatalf("first scan probed %d times, want 1", probes)
	}
	if len(store.paths) != 1 {
		t.Fatalf("first scan banked %d durations, want 1", len(store.paths))
	}

	if _, err := sc.ScanLibrary(context.Background(), dir, opts); err != nil {
		t.Fatalf("second ScanLibrary: %v", err)
	}
	if probes != 1 {
		t.Fatalf("second scan probed again (total %d, want 1); the cache gate is not holding and the disk never idles", probes)
	}
	if len(store.paths) != 1 {
		t.Fatalf("second scan banked another row (total %d, want 1)", len(store.paths))
	}
}

// A lookup error must fail CLOSED toward not reading. Treating an errored lookup
// as "absent" would re-probe the entire library on every scan whenever the DB is
// unhappy -- a silent, disk-thrashing degrade.
func TestScanDoesNotProbeSkippedFileWhenLookupErrors(t *testing.T) {
	dir := t.TempDir()
	const sampleRate, totalSamples uint32 = 44100, 44100 * 210
	if err := testutil.WriteFLACFile(dir, "song.flac", sampleRate, totalSamples); err != nil {
		t.Fatalf("write fixture: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "song.lrc"), []byte("[00:01.00]words\n"), 0o600); err != nil {
		t.Fatalf("write .lrc: %v", err)
	}

	store := &recordingDurationStore{lookupErr: errors.New("database is locked")}
	sc := NewScanner(WithDurationStore(store))
	probes := 0
	sc.probeFunc = func(string) (int, error) {
		probes++
		return 210, nil
	}

	if _, err := sc.ScanLibrary(context.Background(), dir, ScanOptions{MaxDepth: 1, EnrichRecording: true}); err != nil {
		t.Fatalf("ScanLibrary: %v", err)
	}
	if probes != 0 {
		t.Fatalf("probed %d times despite a lookup error, want 0 (must fail closed toward not reading)", probes)
	}
}

// Enrichment off means the scanner probes no headers at all. The skipped-file
// bank must not become a back door around that switch (#217).
func TestScanDoesNotBankForSkippedFileWhenEnrichmentDisabled(t *testing.T) {
	dir := t.TempDir()
	const sampleRate, totalSamples uint32 = 44100, 44100 * 210
	if err := testutil.WriteFLACFile(dir, "song.flac", sampleRate, totalSamples); err != nil {
		t.Fatalf("write fixture: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "song.lrc"), []byte("[00:01.00]words\n"), 0o600); err != nil {
		t.Fatalf("write .lrc: %v", err)
	}

	store := &recordingDurationStore{}
	sc := NewScanner(WithDurationStore(store))
	probes := 0
	sc.probeFunc = func(string) (int, error) {
		probes++
		return 210, nil
	}

	if _, err := sc.ScanLibrary(context.Background(), dir, ScanOptions{MaxDepth: 1, EnrichRecording: false}); err != nil {
		t.Fatalf("ScanLibrary: %v", err)
	}
	if probes != 0 {
		t.Fatalf("probed %d times with enrichment off, want 0", probes)
	}
	if len(store.paths) != 0 {
		t.Fatalf("banked %d durations with enrichment off, want 0", len(store.paths))
	}
}

// With enrichment off the scanner never probes the duration, so there is nothing
// to bank and the store must not be touched.
func TestScanRecordsNothingWhenEnrichmentDisabled(t *testing.T) {
	dir := t.TempDir()
	const sampleRate, totalSamples uint32 = 44100, 44100 * 210
	if err := testutil.WriteFLACFile(dir, "song.flac", sampleRate, totalSamples); err != nil {
		t.Fatalf("write fixture: %v", err)
	}

	store := &recordingDurationStore{}
	sc := NewScanner(WithDurationStore(store))

	results, err := sc.ScanLibrary(context.Background(), dir, ScanOptions{MaxDepth: 1, EnrichRecording: false})
	if err != nil {
		t.Fatalf("ScanLibrary: %v", err)
	}
	if len(results) != 1 {
		t.Fatalf("got %d results; want 1 (track must still be scanned)", len(results))
	}

	if len(store.paths) != 0 {
		t.Fatalf("recorded %d durations with enrichment off, want 0", len(store.paths))
	}
}

// TestScanRecordsDurationFromOpenHandleNotPath pins the fix for the defect
// where recordDuration stamped the cache row with a path-based stat
// (os.DirEntry.Info()) taken AFTER the header read, rather than a stat of the
// already-open file handle the duration was actually read from. A path-based
// stat is vulnerable to a tagger's write-tmp-then-rename swapping the file
// between the header read and the stat, banking a wrong duration under a new
// file's mtime/size, where it would validate as fresh forever.
//
// A live mid-scan rename race is impractical to force deterministically at
// the scheduler level, but the discriminating half of it -- "does the stamp
// come from the open fd or from re-resolving the path" -- is directly
// testable on Unix: an already-open fd keeps referring to its original inode
// even after the directory entry at that path is repointed by rename(2). So
// the probeFunc test seam (invoked immediately before recordDuration, see
// probeDuration) performs exactly that swap -- renaming a differently-sized
// replacement file over the scanned path -- between the header read and the
// stamp. A handle-derived stat (f.Stat(), the fix) is blind to the swap and
// still reports the ORIGINAL file's mtime/size; a path-derived stat
// (entry.Info(), the pre-fix bug) lazily re-Lstats the path at call time and
// picks up the REPLACEMENT file's mtime/size instead. This test asserts the
// former and, run against the pre-fix code, fails by observing the latter --
// see the git history for the empirical check.
func TestScanRecordsDurationFromOpenHandleNotPath(t *testing.T) {
	dir := t.TempDir()
	const sampleRate, totalSamples uint32 = 44100, 44100 * 210
	if err := testutil.WriteFLACFile(dir, "song.flac", sampleRate, totalSamples); err != nil {
		t.Fatalf("write fixture: %v", err)
	}
	path := filepath.Join(dir, "song.flac")

	wantInfo, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat fixture: %v", err)
	}

	store := &recordingDurationStore{}
	sc := NewScanner(WithDurationStore(store))

	// The swap happens inside probeFunc, which runs at exactly the point the
	// production code calls probeDuration -- immediately before recordDuration,
	// after the header (and open fd) already exist. Writing the replacement to
	// a temp name and renaming it over path (rather than truncating path in
	// place) is what makes the fd and the path diverge: rename repoints the
	// directory entry to a new inode while the already-open fd keeps its old
	// one, mirroring a tagger's write-tmp-then-rename.
	sc.probeFunc = func(p string) (int, error) {
		if p != path {
			return 210, nil
		}
		// A VORBIS_COMMENT block makes the replacement a different size than
		// the header-only original, so a path re-stat is distinguishable from
		// the handle stat by size alone.
		replacement := testutil.GenerateFLACExtended(sampleRate, totalSamples, map[string]string{"TITLE": "swapped"})
		tmp := path + ".swap"
		if err := os.WriteFile(tmp, replacement, 0o644); err != nil { //nolint:gosec // test fixture file
			return 0, fmt.Errorf("write replacement: %w", err)
		}
		if err := os.Rename(tmp, path); err != nil {
			return 0, fmt.Errorf("swap replacement over original: %w", err)
		}
		return 210, nil
	}

	results, err := sc.ScanLibrary(context.Background(), dir, ScanOptions{MaxDepth: 1, EnrichRecording: true})
	if err != nil {
		t.Fatalf("ScanLibrary: %v", err)
	}
	if len(results) != 1 {
		t.Fatalf("got %d results; want 1", len(results))
	}
	if len(store.paths) != 1 {
		t.Fatalf("recorded %d durations, want 1", len(store.paths))
	}

	// Sanity: confirm the swap actually changed what's on disk, else the test
	// proves nothing regardless of which stat source recordDuration used.
	replacedInfo, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat replacement: %v", err)
	}
	if replacedInfo.Size() == wantInfo.Size() {
		t.Fatalf("replacement file is the same size (%d) as the original; swap did not change the on-disk file, test cannot discriminate", replacedInfo.Size())
	}

	if got, want := store.sizes[0], wantInfo.Size(); got != want {
		t.Errorf("recorded size %d, want %d (size of the ORIGINAL file via the open handle, not the replacement at the same path)", got, want)
	}
	if got, want := store.mtimes[0], wantInfo.ModTime().UnixNano(); got != want {
		t.Errorf("recorded mtime %d, want %d (mtime of the ORIGINAL file via the open handle, not the replacement at the same path)", got, want)
	}
}

// TestScanRecordsNothingForZeroDuration directly exercises recordDuration's
// seconds<=0 guard, which scanDir relies on since it always calls
// recordDuration regardless of whether probeDuration succeeded (a parse
// failure degrades to duration 0, not a skipped call). Without this guard a
// zero/unparsable duration would bank a bogus row that reads as "measured
// zero-length" rather than "never read", so the guard is load-bearing, not
// defensive.
func TestScanRecordsNothingForZeroDuration(t *testing.T) {
	dir := t.TempDir()
	const sampleRate, totalSamples uint32 = 44100, 44100 * 210
	if err := testutil.WriteFLACFile(dir, "song.flac", sampleRate, totalSamples); err != nil {
		t.Fatalf("write fixture: %v", err)
	}

	store := &recordingDurationStore{}
	sc := NewScanner(WithDurationStore(store))
	// probeFunc stands in for a parse failure: probeDuration returns 0 with no
	// error, exactly what audioDuration degrades to on an unparsable header.
	sc.probeFunc = func(string) (int, error) { return 0, nil }

	results, err := sc.ScanLibrary(context.Background(), dir, ScanOptions{MaxDepth: 1, EnrichRecording: true})
	if err != nil {
		t.Fatalf("ScanLibrary: %v", err)
	}
	if len(results) != 1 {
		t.Fatalf("got %d results; want 1", len(results))
	}

	if len(store.paths) != 0 {
		t.Fatalf("recorded %d durations for a zero duration, want 0", len(store.paths))
	}
}

// lookupDurationStore is a minimal in-memory audiodur.Store stand-in keyed
// exactly like the real table (file_path is the whole key; mtime/size are
// stored alongside but not needed to prove the KEY-collapse property this
// test targets). It lets the test assert a real cache HIT, not just that two
// path strings look equal in prose.
type lookupDurationStore struct {
	rows map[string]int
}

func (s *lookupDurationStore) Record(_ context.Context, path string, _, _ int64, seconds int) error {
	if s.rows == nil {
		s.rows = make(map[string]int)
	}
	s.rows[path] = seconds
	return nil
}

// Lookup ignores mtime/size on purpose: file_path is the whole primary key in
// the real table, and the property this store exists to prove is KEY COLLAPSE
// (#643) -- that two spellings of one file resolve to a single row. Validating
// the stamp here would add a second reason for a miss and blur that signal.
func (s *lookupDurationStore) Lookup(_ context.Context, path string, _, _ int64) (int, bool, error) {
	seconds, ok := s.rows[path]
	return seconds, ok, nil
}

// TestScanLibrary_SymlinkedRootCollapsesToOneCanonicalKey exercises the #643
// fix end-to-end against a REAL symlinked directory layout, the deployment
// shape the issue was filed against (a container's /music mounted as a
// symlink to the array's real path, e.g. /music -> /mnt/array/music).
//
// It asserts two things a prose claim cannot stand in for:
//  1. The key the scanner actually writes is the canonical (symlink-resolved)
//     spelling, not the configured root's literal, possibly-symlinked one.
//  2. A lookup keyed the way a consumer would key it -- by canonicalizing
//     whatever source path it was handed, exactly as worker.recordDuration
//     now does via pathutil.CanonicalPath -- actually HITS the row the scan
//     wrote, whether that consumer's own path happened to be spelled via the
//     symlink or via the real target.
func TestScanLibrary_SymlinkedRootCollapsesToOneCanonicalKey(t *testing.T) {
	base := t.TempDir()
	realRoot := filepath.Join(base, "real-array-music")
	if err := os.MkdirAll(realRoot, 0o755); err != nil {
		t.Fatalf("mkdir real root: %v", err)
	}
	symlinkRoot := filepath.Join(base, "music")
	if err := os.Symlink(realRoot, symlinkRoot); err != nil {
		t.Skipf("symlinks unsupported here: %v", err)
	}

	const sampleRate, totalSamples uint32 = 44100, 44100 * 210
	if err := testutil.WriteFLACFile(realRoot, "song.flac", sampleRate, totalSamples); err != nil {
		t.Fatalf("write fixture: %v", err)
	}

	// The library root as an operator would configure it: the symlink path,
	// not the real target.
	store := &lookupDurationStore{}
	sc := NewScanner(WithDurationStore(store))
	results, err := sc.ScanLibrary(context.Background(), symlinkRoot, ScanOptions{MaxDepth: 1, EnrichRecording: true})
	if err != nil {
		t.Fatalf("ScanLibrary: %v", err)
	}
	if len(results) != 1 {
		t.Fatalf("got %d results; want 1", len(results))
	}

	wantKey, err := filepath.EvalSymlinks(filepath.Join(realRoot, "song.flac"))
	if err != nil {
		t.Fatalf("EvalSymlinks real path: %v", err)
	}
	if len(store.rows) != 1 {
		t.Fatalf("recorded %d rows, want 1", len(store.rows))
	}
	if _, ok := store.rows[wantKey]; !ok {
		t.Fatalf("scan wrote key(s) %v; want the canonical key %q present", mapKeys(store.rows), wantKey)
	}

	// Consumer side: a webhook-created item's SourcePath comes pre-resolved by
	// pathutil.ResolveWithinRoot (internal/server.confinedPayloadPath) against
	// the SAME configured (symlink) root.
	webhookSourcePath, ok := pathutil.ResolveWithinRoot(symlinkRoot, filepath.Join(symlinkRoot, "song.flac"))
	if !ok {
		t.Fatal("ResolveWithinRoot rejected the fixture path")
	}
	// A scan-enqueued item's SourcePath is the scanner's raw (unresolved)
	// ScanResult.FilePath -- the configured root's literal spelling, joined
	// with the walked filename (models.ScanResult is built from dir+file.Name,
	// not from the canonicalized recordDuration key).
	scanSourcePath := results[0].FilePath

	for name, consumerPath := range map[string]string{
		"webhook-resolved source path": webhookSourcePath,
		"scan-enqueued source path":    scanSourcePath,
	} {
		t.Run(name, func(t *testing.T) {
			// Mirrors worker.recordDuration's key derivation exactly
			// (pathutil.CanonicalPath), so this proves the worker capture site
			// and the scanner capture site land on the identical row.
			key := pathutil.CanonicalPath(consumerPath)
			// mtime/size are ignored by this store by design -- see its Lookup.
			seconds, hit, err := store.Lookup(context.Background(), key, 0, 0)
			if err != nil {
				t.Fatalf("Lookup: %v", err)
			}
			if !hit {
				t.Fatalf("consumer path %q (canonicalized to %q) missed the cache; scan wrote key %q", consumerPath, key, wantKey)
			}
			if seconds != 210 {
				t.Errorf("looked up %ds, want 210s", seconds)
			}
		})
	}
}

func mapKeys(m map[string]int) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	return keys
}

func TestReadAudioFactsReadsFullTagSet(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "track.mp3")
	// WriteAudioFileExtended is the existing testutil fixture helper for ID3-tagged audio.
	if err := testutil.WriteAudioFileExtended(dir, "track.mp3", "Test Artist", "Test Title", "Test Album", "", map[string]string{
		"TPE2": "Test Album Artist",
		"TCOM": "Test Composer",
		"TCON": "Test Genre",
		"TDRC": "1997",
		"TRCK": "3/12",
		"TPOS": "1/2",
		"TSRC": "US-TEST-97-00123",
	}, map[string]string{
		"musicbrainz_recordingid": "test-mbid-uuid",
	}); err != nil {
		t.Fatalf("WriteAudioFileExtended: %v", err)
	}

	got, err := ReadAudioFacts(path)
	if err != nil {
		t.Fatalf("ReadAudioFacts: %v", err)
	}

	if got.Artist != "Test Artist" {
		t.Errorf("Artist = %q, want %q", got.Artist, "Test Artist")
	}
	if got.AlbumArtist != "Test Album Artist" {
		t.Errorf("AlbumArtist = %q, want %q", got.AlbumArtist, "Test Album Artist")
	}
	if got.Title != "Test Title" {
		t.Errorf("Title = %q, want %q", got.Title, "Test Title")
	}
	if got.Album != "Test Album" {
		t.Errorf("Album = %q, want %q", got.Album, "Test Album")
	}
	if got.Composer != "Test Composer" {
		t.Errorf("Composer = %q, want %q", got.Composer, "Test Composer")
	}
	if got.Genre != "Test Genre" {
		t.Errorf("Genre = %q, want %q", got.Genre, "Test Genre")
	}
	if got.Year != 1997 {
		t.Errorf("Year = %d, want 1997", got.Year)
	}
	if got.TrackNo != 3 || got.TrackTotal != 12 {
		t.Errorf("Track = %d/%d, want 3/12", got.TrackNo, got.TrackTotal)
	}
	if got.DiscNo != 1 || got.DiscTotal != 2 {
		t.Errorf("Disc = %d/%d, want 1/2", got.DiscNo, got.DiscTotal)
	}
	if got.Format == "" || got.FileType == "" {
		t.Errorf("Format/FileType = %q/%q, want both non-empty", got.Format, got.FileType)
	}
	// Identity comes from the open handle's own Stat, never a path re-stat.
	if got.MTimeNano == 0 || got.SizeBytes == 0 {
		t.Errorf("MTimeNano/SizeBytes = %d/%d, want both non-zero", got.MTimeNano, got.SizeBytes)
	}
	if got.MBID != "test-mbid-uuid" {
		t.Errorf("MBID = %q, want %q", got.MBID, "test-mbid-uuid")
	}
	if got.ISRC != "US-TEST-97-00123" {
		t.Errorf("ISRC = %q, want %q", got.ISRC, "US-TEST-97-00123")
	}
}

func TestReadAudioFactsAbsentTagsAreSentinelsNotErrors(t *testing.T) {
	// A file with only the minimum tags: every other field must come back as its
	// documented zero-value sentinel, and this must NOT be an error.
	dir := t.TempDir()
	path := filepath.Join(dir, "track.mp3")
	if err := testutil.WriteAudioFile(dir, "track.mp3", "", "Only Title", "", ""); err != nil {
		t.Fatalf("WriteAudioFile: %v", err)
	}

	got, err := ReadAudioFacts(path)
	if err != nil {
		t.Fatalf("absent tags must not error: %v", err)
	}
	if got.Title != "Only Title" {
		t.Errorf("Title = %q, want %q", got.Title, "Only Title")
	}
	if got.Genre != "" || got.Composer != "" {
		t.Errorf("absent string tags = %q/%q, want empty sentinels", got.Genre, got.Composer)
	}
	if got.Year != 0 || got.TrackNo != 0 || got.DiscNo != 0 {
		t.Errorf("absent numeric tags = %d/%d/%d, want 0 sentinels", got.Year, got.TrackNo, got.DiscNo)
	}
}

func TestReadAudioFactsOpenFailureIsAnError(t *testing.T) {
	_, err := ReadAudioFacts(filepath.Join(t.TempDir(), "does-not-exist.mp3"))
	if err == nil {
		t.Fatal("a missing file must return an error, not a zero-value struct")
	}
}

func TestReadAudioFactsNeverExposesLyricsOrPicture(t *testing.T) {
	// Guards the deliberate exclusion: lyric text must never enter the DB
	// (copyright, and it would give the #538 extracted lane a self-ingestion
	// route), and cover art would dwarf every other column. A reflective check
	// so adding such a field later fails loudly rather than silently shipping.
	tp := reflect.TypeOf(AudioFacts{})
	for i := 0; i < tp.NumField(); i++ {
		name := strings.ToLower(tp.Field(i).Name)
		if strings.Contains(name, "lyric") || strings.Contains(name, "picture") || strings.Contains(name, "artwork") {
			t.Errorf("AudioFacts must not carry field %q: lyrics and cover art are deliberately excluded", tp.Field(i).Name)
		}
	}
}
